-- Create lots table (core diamond manufacturing lots)
CREATE TABLE IF NOT EXISTS lots (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  lot_id VARCHAR(50) NOT NULL UNIQUE,
  lot_name VARCHAR(255) NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  shape VARCHAR(100) NOT NULL,
  shape_category ENUM('ROUND', 'FANCY', 'BLOCKING') NOT NULL,
  qty INT UNSIGNED NOT NULL,
  issue_weight DECIMAL(12, 4) NOT NULL,
  estimate_wt DECIMAL(12, 4) NOT NULL,
  issue_date DATE NOT NULL,
  labour_head_id INT UNSIGNED NOT NULL,
  status ENUM('ISSUED', 'IN_PROGRESS', 'RECEIVED', 'VERIFIED', 'REWORK', 'LOST') NOT NULL DEFAULT 'ISSUED',
  received_date DATE NULL,
  polished_wt DECIMAL(12, 4) NULL,
  color VARCHAR(10) NULL,
  clarity VARCHAR(10) NULL,
  cut VARCHAR(50) NULL,
  grader VARCHAR(100) NULL,
  lab ENUM('IGI', 'GIA', 'US') NULL,
  remarks TEXT NULL,
  days_consumed INT UNSIGNED NULL,
  weight_diff DECIMAL(12, 4) NULL,
  labour_amount DECIMAL(12, 2) NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (employee_id) REFERENCES employees(id),
  FOREIGN KEY (labour_head_id) REFERENCES labour_heads(id),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_lots_employee_id (employee_id),
  INDEX idx_lots_status (status),
  INDEX idx_lots_issue_date (issue_date),
  INDEX idx_lots_shape_category (shape_category),
  INDEX idx_lots_lab (lab),
  INDEX idx_lots_deleted_at (deleted_at),
  INDEX idx_lots_status_employee (status, employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
