-- Create salary lines table (per-employee salary per period with two-man verification)
CREATE TABLE IF NOT EXISTS salary_lines (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  period_id INT UNSIGNED NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  total_cts DECIMAL(12, 4) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  lots_count INT UNSIGNED NOT NULL DEFAULT 0,
  manager_verified BOOLEAN NOT NULL DEFAULT false,
  manager_verified_by INT UNSIGNED NULL,
  manager_verified_at DATETIME NULL,
  account_verified BOOLEAN NOT NULL DEFAULT false,
  account_verified_by INT UNSIGNED NULL,
  account_verified_at DATETIME NULL,
  paid_at DATE NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (period_id) REFERENCES salary_periods(id) ON DELETE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id),
  FOREIGN KEY (manager_verified_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (account_verified_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_period_employee (period_id, employee_id),
  INDEX idx_salary_lines_period (period_id),
  INDEX idx_salary_lines_employee (employee_id),
  INDEX idx_salary_lines_verification (manager_verified, account_verified)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
