-- Create attendance records table (one row per employee per day)
CREATE TABLE IF NOT EXISTS attendance_records (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employee_id INT UNSIGNED NOT NULL,
  att_date DATE NOT NULL,
  status ENUM('PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE', 'HOLIDAY', 'WEEK_OFF') NOT NULL,
  shift_id INT UNSIGNED NULL,
  leave_type_id INT UNSIGNED NULL,
  in_time TIME NULL,
  out_time TIME NULL,
  worked_hours DECIMAL(5, 2) NULL,
  ot_hours DECIMAL(5, 2) NOT NULL DEFAULT 0,
  is_late BOOLEAN NOT NULL DEFAULT false,
  source ENUM('MANUAL', 'IMPORT', 'LEAVE_SYNC', 'SELF_PUNCH') NOT NULL DEFAULT 'MANUAL',
  remarks VARCHAR(255) NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (shift_id) REFERENCES shifts(id) ON DELETE SET NULL,
  FOREIGN KEY (leave_type_id) REFERENCES leave_types(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_attendance_emp_date (employee_id, att_date),
  INDEX idx_attendance_date (att_date),
  INDEX idx_attendance_status (status),
  INDEX idx_attendance_date_status (att_date, status),
  INDEX idx_attendance_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
