-- Create recruitment tables (job openings and candidate pipeline)
CREATE TABLE IF NOT EXISTS job_openings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  department VARCHAR(100) NULL,
  grade VARCHAR(20) NULL,
  worker_type ENUM('PIECE_RATE', 'DHAR', 'MAXI') NOT NULL DEFAULT 'PIECE_RATE',
  openings INT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('OPEN', 'ON_HOLD', 'CLOSED') NOT NULL DEFAULT 'OPEN',
  opened_at DATE NOT NULL,
  closed_at DATE NULL,
  notes TEXT NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_openings_status (status),
  INDEX idx_openings_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS candidates (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(255) NULL,
  opening_id INT UNSIGNED NULL,
  position_grade VARCHAR(20) NOT NULL,
  worker_type ENUM('PIECE_RATE', 'DHAR', 'MAXI') NOT NULL DEFAULT 'PIECE_RATE',
  expected_salary DECIMAL(12, 2) NULL,
  experience_years DECIMAL(4, 1) NULL,
  source VARCHAR(100) NULL,
  status ENUM('APPLIED', 'INTERVIEW', 'SELECTED', 'JOINED', 'REJECTED') NOT NULL DEFAULT 'APPLIED',
  interview_date DATETIME NULL,
  notes TEXT NULL,
  converted_employee_id INT UNSIGNED NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (opening_id) REFERENCES job_openings(id) ON DELETE SET NULL,
  FOREIGN KEY (converted_employee_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_candidates_status (status),
  INDEX idx_candidates_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
