-- Prior employment history and references
CREATE TABLE IF NOT EXISTS employee_experience (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employee_id INT UNSIGNED NOT NULL,
  company_name VARCHAR(200) NOT NULL,
  designation VARCHAR(160) NULL,
  employment_type ENUM('PERMANENT', 'CONTRACT', 'PART_TIME', 'INTERNSHIP', 'FREELANCE') NULL,
  industry VARCHAR(120) NULL,
  location VARCHAR(120) NULL,
  from_date DATE NOT NULL,
  to_date DATE NULL,
  is_current BOOLEAN NOT NULL DEFAULT false,
  last_salary DECIMAL(12, 2) NULL,
  reason_for_leaving VARCHAR(255) NULL,
  projects TEXT NULL,
  reference_name VARCHAR(160) NULL,
  reference_designation VARCHAR(160) NULL,
  reference_phone VARCHAR(20) NULL,
  reference_email VARCHAR(255) NULL,
  document_id INT UNSIGNED NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (document_id) REFERENCES employee_documents(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_experience_employee (employee_id),
  INDEX idx_experience_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
