-- Organization core: companies, legal entities and the geography tree.
CREATE TABLE IF NOT EXISTS companies (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  short_name VARCHAR(60) NULL,
  parent_company_id INT UNSIGNED NULL,
  company_type ENUM('HOLDING', 'SUBSIDIARY', 'BRANCH_OFFICE', 'FRANCHISE', 'JOINT_VENTURE', 'STANDALONE') NOT NULL DEFAULT 'STANDALONE',
  industry_type VARCHAR(120) NULL,
  registration_no VARCHAR(60) NULL,
  cin VARCHAR(40) NULL,
  gstin VARCHAR(20) NULL,
  vat_number VARCHAR(30) NULL,
  pan VARCHAR(10) NULL,
  tan VARCHAR(15) NULL,
  incorporated_on DATE NULL,
  fiscal_year_start_month TINYINT UNSIGNED NOT NULL DEFAULT 4,
  base_currency CHAR(3) NOT NULL DEFAULT 'INR',
  default_language VARCHAR(10) NOT NULL DEFAULT 'en',
  default_timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Kolkata',
  country VARCHAR(2) NOT NULL DEFAULT 'IN',
  corporate_address TEXT NULL,
  contact_email VARCHAR(255) NULL,
  contact_phone VARCHAR(30) NULL,
  website VARCHAR(255) NULL,
  logo_url VARCHAR(500) NULL,
  brand_color VARCHAR(20) NULL,
  is_payroll_company BOOLEAN NOT NULL DEFAULT true,
  status ENUM('ACTIVE', 'INACTIVE', 'DISSOLVED') NOT NULL DEFAULT 'ACTIVE',
  notes TEXT NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (parent_company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_companies_parent (parent_company_id),
  INDEX idx_companies_status (status),
  INDEX idx_companies_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS legal_entities (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id INT UNSIGNED NOT NULL,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  entity_type ENUM('PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'LLP', 'PARTNERSHIP', 'PROPRIETORSHIP', 'TRUST', 'OTHER') NOT NULL DEFAULT 'PRIVATE_LIMITED',
  registration_no VARCHAR(60) NULL,
  tax_id VARCHAR(40) NULL,
  gstin VARCHAR(20) NULL,
  country VARCHAR(2) NOT NULL DEFAULT 'IN',
  state VARCHAR(100) NULL,
  registered_address TEXT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  is_payroll_entity BOOLEAN NOT NULL DEFAULT true,
  status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_entities_company (company_id),
  INDEX idx_entities_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Self-parenting geography: global region > country > state > zone > territory.
CREATE TABLE IF NOT EXISTS regions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(160) NOT NULL,
  region_type ENUM('GLOBAL', 'COUNTRY', 'STATE', 'ZONE', 'TERRITORY', 'SALES', 'OPERATIONAL') NOT NULL DEFAULT 'ZONE',
  parent_region_id INT UNSIGNED NULL,
  country VARCHAR(2) NULL,
  head_employee_id INT UNSIGNED NULL,
  status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (parent_region_id) REFERENCES regions(id) ON DELETE SET NULL,
  FOREIGN KEY (head_employee_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_regions_parent (parent_region_id),
  INDEX idx_regions_type (region_type),
  INDEX idx_regions_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
