-- Physical and virtual capture endpoints. A device authenticates to the sync
-- API with a bearer key -- only the hash is stored, the plaintext is shown once
-- at registration, same contract as an API token.
CREATE TABLE IF NOT EXISTS attendance_devices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(150) NOT NULL,
  device_type ENUM('BIOMETRIC', 'FACE', 'QR_KIOSK', 'NFC_READER', 'RFID_READER', 'WEB_KIOSK', 'MOBILE', 'TURNSTILE', 'PALM', 'IRIS') NOT NULL DEFAULT 'BIOMETRIC',
  vendor VARCHAR(100) NULL,
  model VARCHAR(100) NULL,
  serial_no VARCHAR(100) NULL,
  firmware_version VARCHAR(50) NULL,
  ip_address VARCHAR(64) NULL,
  mac_address VARCHAR(64) NULL,
  company_id INT UNSIGNED NULL,
  branch_id INT UNSIGNED NULL,
  location_id INT UNSIGNED NULL,
  geofence_id INT UNSIGNED NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
  api_key_hash VARCHAR(255) NULL,
  api_key_hint VARCHAR(20) NULL,
  supports_in_out BOOLEAN NOT NULL DEFAULT true,
  default_punch_type ENUM('AUTO', 'IN', 'OUT') NOT NULL DEFAULT 'AUTO',
  sync_mode ENUM('PUSH', 'PULL', 'MANUAL') NOT NULL DEFAULT 'PUSH',
  sync_interval_minutes INT UNSIGNED NOT NULL DEFAULT 15,
  heartbeat_interval_minutes INT UNSIGNED NOT NULL DEFAULT 5,
  last_heartbeat_at TIMESTAMP NULL,
  last_sync_at TIMESTAMP NULL,
  last_punch_at TIMESTAMP NULL,
  total_punches BIGINT UNSIGNED NOT NULL DEFAULT 0,
  enrolled_count INT UNSIGNED NOT NULL DEFAULT 0,
  health_status ENUM('ONLINE', 'OFFLINE', 'DEGRADED', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  health_note VARCHAR(255) NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED') NOT NULL DEFAULT 'ACTIVE',
  config JSON NULL,
  installed_on DATE NULL,
  warranty_expires_on DATE NULL,
  notes TEXT NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_device_code (code),
  INDEX idx_device_branch (branch_id),
  INDEX idx_device_type (device_type),
  INDEX idx_device_health (health_status),
  INDEX idx_device_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One row per sync batch, so a gap in attendance can be traced to the batch
-- that failed rather than guessed at.
CREATE TABLE IF NOT EXISTS device_sync_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id INT UNSIGNED NOT NULL,
  sync_type ENUM('PUSH', 'PULL', 'MANUAL', 'HEARTBEAT', 'CONFIG') NOT NULL DEFAULT 'PUSH',
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMP NULL,
  duration_ms INT UNSIGNED NULL,
  status ENUM('SUCCESS', 'PARTIAL', 'FAILED', 'RUNNING') NOT NULL DEFAULT 'RUNNING',
  records_received INT UNSIGNED NOT NULL DEFAULT 0,
  records_accepted INT UNSIGNED NOT NULL DEFAULT 0,
  records_duplicate INT UNSIGNED NOT NULL DEFAULT 0,
  records_rejected INT UNSIGNED NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  payload_hash VARCHAR(64) NULL,
  triggered_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (device_id) REFERENCES attendance_devices(id) ON DELETE CASCADE,
  FOREIGN KEY (triggered_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_sync_device_time (device_id, started_at),
  INDEX idx_sync_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Maps our employee id to whatever enrolment id the device knows them by.
-- Without this a biometric export full of device-local ids cannot be resolved.
CREATE TABLE IF NOT EXISTS device_enrollments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id INT UNSIGNED NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  device_user_id VARCHAR(64) NOT NULL,
  enrollment_type ENUM('FINGERPRINT', 'FACE', 'PALM', 'IRIS', 'CARD', 'PIN') NOT NULL DEFAULT 'FINGERPRINT',
  templates_count INT UNSIGNED NOT NULL DEFAULT 0,
  quality_score DECIMAL(5, 2) NULL,
  enrolled_at TIMESTAMP NULL,
  last_verified_at TIMESTAMP NULL,
  status ENUM('ACTIVE', 'INACTIVE', 'PENDING', 'FAILED') NOT NULL DEFAULT 'ACTIVE',
  notes VARCHAR(255) NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (device_id) REFERENCES attendance_devices(id) ON DELETE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_device_user (device_id, device_user_id),
  INDEX idx_enroll_employee (employee_id),
  INDEX idx_enroll_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
