-- A break is a BREAK_OUT/BREAK_IN pair resolved into minutes. Unpaid minutes
-- are what the punch engine subtracts from gross hours -- paid ones are
-- recorded but never deducted.
CREATE TABLE IF NOT EXISTS attendance_breaks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  attendance_id INT UNSIGNED NULL,
  employee_id INT UNSIGNED NOT NULL,
  att_date DATE NOT NULL,
  break_type_id INT UNSIGNED NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  minutes INT UNSIGNED NOT NULL DEFAULT 0,
  is_paid BOOLEAN NOT NULL DEFAULT false,
  is_open BOOLEAN NOT NULL DEFAULT false,
  exceeded_by_minutes INT UNSIGNED NOT NULL DEFAULT 0,
  approval_status ENUM('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'NOT_REQUIRED',
  approved_by INT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  start_punch_id BIGINT UNSIGNED NULL,
  end_punch_id BIGINT UNSIGNED NULL,
  source ENUM('PUNCH', 'MANUAL', 'POLICY', 'IMPORT') NOT NULL DEFAULT 'PUNCH',
  remarks VARCHAR(255) NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (attendance_id) REFERENCES attendance_records(id) ON DELETE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (break_type_id) REFERENCES break_types(id) ON DELETE SET NULL,
  FOREIGN KEY (start_punch_id) REFERENCES attendance_punches(id) ON DELETE SET NULL,
  FOREIGN KEY (end_punch_id) REFERENCES attendance_punches(id) ON DELETE SET NULL,
  FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_break_emp_date (employee_id, att_date),
  INDEX idx_break_attendance (attendance_id),
  INDEX idx_break_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Overtime as its own ledger. attendance_records.ot_hours stays the raw derived
-- figure -- this table records what was asked for, what was approved, at which
-- multiplier, and is the only thing payroll should pay against.
CREATE TABLE IF NOT EXISTS overtime_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employee_id INT UNSIGNED NOT NULL,
  att_date DATE NOT NULL,
  attendance_id INT UNSIGNED NULL,
  request_id INT UNSIGNED NULL,
  ot_type ENUM('WEEKDAY', 'WEEK_OFF', 'HOLIDAY', 'NIGHT') NOT NULL DEFAULT 'WEEKDAY',
  derived_hours DECIMAL(5, 2) NOT NULL DEFAULT 0,
  requested_hours DECIMAL(5, 2) NOT NULL DEFAULT 0,
  approved_hours DECIMAL(5, 2) NOT NULL DEFAULT 0,
  multiplier DECIMAL(4, 2) NOT NULL DEFAULT 1.00,
  payable_hours DECIMAL(6, 2) NOT NULL DEFAULT 0,
  hourly_rate DECIMAL(10, 2) NULL,
  amount DECIMAL(12, 2) NULL,
  status ENUM('DERIVED', 'PENDING', 'APPROVED', 'REJECTED', 'PAID', 'CANCELLED') NOT NULL DEFAULT 'DERIVED',
  reason VARCHAR(500) NULL,
  approved_by INT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  paid_period_id INT UNSIGNED NULL,
  company_id INT UNSIGNED NULL,
  branch_id INT UNSIGNED NULL,
  department_id INT UNSIGNED NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (attendance_id) REFERENCES attendance_records(id) ON DELETE SET NULL,
  FOREIGN KEY (request_id) REFERENCES attendance_requests(id) ON DELETE SET NULL,
  FOREIGN KEY (paid_period_id) REFERENCES salary_periods(id) ON DELETE SET NULL,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
  FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_ot_employee_date (employee_id, att_date),
  INDEX idx_ot_status (status, att_date),
  INDEX idx_ot_date (att_date),
  INDEX idx_ot_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
