-- Non-employee people on site. Kept out of employees so headcount, payroll and
-- the org chart are never polluted by a contractor or a walk-in visitor.
CREATE TABLE IF NOT EXISTS visitors (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  visitor_code VARCHAR(40) NOT NULL,
  visitor_type ENUM('VISITOR', 'CONTRACTOR', 'VENDOR', 'TEMP_STAFF', 'INTERN', 'AUDITOR', 'CLIENT') NOT NULL DEFAULT 'VISITOR',
  full_name VARCHAR(150) NOT NULL,
  company_name VARCHAR(150) NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(150) NULL,
  id_proof_type VARCHAR(50) NULL,
  id_proof_no VARCHAR(80) NULL,
  photo_path VARCHAR(500) NULL,
  nationality VARCHAR(60) NULL,
  contractor_agency VARCHAR(150) NULL,
  contract_from DATE NULL,
  contract_to DATE NULL,
  daily_rate DECIMAL(10, 2) NULL,
  is_blacklisted BOOLEAN NOT NULL DEFAULT false,
  blacklist_reason VARCHAR(255) NULL,
  notes TEXT NULL,
  company_id INT UNSIGNED NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_visitor_code (visitor_code),
  INDEX idx_visitor_type (visitor_type),
  INDEX idx_visitor_name (full_name),
  INDEX idx_visitor_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One row per check-in. A contractor working thirty days has thirty visits,
-- which is what a contractor attendance report is actually counting.
CREATE TABLE IF NOT EXISTS visitor_visits (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  visitor_id INT UNSIGNED NOT NULL,
  visit_date DATE NOT NULL,
  host_employee_id INT UNSIGNED NULL,
  purpose VARCHAR(255) NULL,
  branch_id INT UNSIGNED NULL,
  location_id INT UNSIGNED NULL,
  badge_no VARCHAR(40) NULL,
  vehicle_no VARCHAR(40) NULL,
  expected_in DATETIME NULL,
  expected_out DATETIME NULL,
  checked_in_at DATETIME NULL,
  checked_out_at DATETIME NULL,
  hours DECIMAL(5, 2) NULL,
  accompanying_count INT UNSIGNED NOT NULL DEFAULT 0,
  belongings VARCHAR(255) NULL,
  approved_by INT UNSIGNED NULL,
  approval_status ENUM('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'NOT_REQUIRED',
  status ENUM('EXPECTED', 'CHECKED_IN', 'CHECKED_OUT', 'NO_SHOW', 'CANCELLED', 'OVERSTAY') NOT NULL DEFAULT 'EXPECTED',
  safety_briefing_done BOOLEAN NOT NULL DEFAULT false,
  remarks VARCHAR(255) NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (visitor_id) REFERENCES visitors(id) ON DELETE CASCADE,
  FOREIGN KEY (host_employee_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
  FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_visit_date (visit_date),
  INDEX idx_visit_visitor_date (visitor_id, visit_date),
  INDEX idx_visit_status (status),
  INDEX idx_visit_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Labour-law rules expressed as thresholds the compliance scan can evaluate.
-- legal_reference is stored so a flagged violation can cite the statute rather
-- than an opaque rule code.
CREATE TABLE IF NOT EXISTS attendance_compliance_rules (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(150) NOT NULL,
  rule_type ENUM('MAX_DAILY_HOURS', 'MAX_WEEKLY_HOURS', 'MIN_REST_HOURS', 'MAX_OT_MONTHLY', 'MAX_OT_WEEKLY', 'MANDATORY_WEEKLY_OFF', 'MAX_CONSECUTIVE_DAYS', 'MANDATORY_BREAK', 'MIN_DAILY_HOURS', 'NIGHT_SHIFT_LIMIT') NOT NULL,
  threshold_value DECIMAL(8, 2) NOT NULL,
  comparison ENUM('GT', 'GTE', 'LT', 'LTE') NOT NULL DEFAULT 'GT',
  period ENUM('DAY', 'WEEK', 'MONTH', 'ROLLING_7', 'ROLLING_30') NOT NULL DEFAULT 'DAY',
  severity ENUM('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL DEFAULT 'MEDIUM',
  country VARCHAR(60) NULL,
  company_id INT UNSIGNED NULL,
  branch_id INT UNSIGNED NULL,
  legal_reference VARCHAR(255) NULL,
  remediation VARCHAR(500) NULL,
  status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_compliance_rule_code (code),
  INDEX idx_compliance_rule_type (rule_type, status),
  INDEX idx_compliance_rule_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attendance_compliance_violations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  rule_id INT UNSIGNED NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  observed_value DECIMAL(10, 2) NOT NULL,
  threshold_value DECIMAL(10, 2) NOT NULL,
  severity ENUM('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL DEFAULT 'MEDIUM',
  detail VARCHAR(500) NULL,
  status ENUM('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'WAIVED') NOT NULL DEFAULT 'OPEN',
  resolved_by INT UNSIGNED NULL,
  resolved_at TIMESTAMP NULL,
  resolution_note VARCHAR(500) NULL,
  company_id INT UNSIGNED NULL,
  branch_id INT UNSIGNED NULL,
  department_id INT UNSIGNED NULL,
  detected_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (rule_id) REFERENCES attendance_compliance_rules(id) ON DELETE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL,
  FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
  FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
  UNIQUE KEY uk_violation_rule_emp_period (rule_id, employee_id, period_start),
  INDEX idx_violation_status (status, severity),
  INDEX idx_violation_employee (employee_id, period_start),
  INDEX idx_violation_detected (detected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Append-only trail for everything the module changes. Kept separate from
-- activity_logs because attendance needs geo coordinates and before/after
-- values on every row, and because retention on it is a compliance question.
CREATE TABLE IF NOT EXISTS attendance_audit_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  entity_type ENUM('PUNCH', 'ATTENDANCE', 'REQUEST', 'APPROVAL', 'SHIFT', 'ROSTER', 'DEVICE', 'POLICY', 'GEOFENCE', 'QR_TOKEN', 'NFC_CARD', 'FACE', 'BREAK', 'OVERTIME', 'VISITOR', 'COMPLIANCE', 'HOLIDAY', 'ASSIGNMENT') NOT NULL,
  entity_id BIGINT UNSIGNED NULL,
  employee_id INT UNSIGNED NULL,
  att_date DATE NULL,
  action VARCHAR(60) NOT NULL,
  summary VARCHAR(500) NULL,
  previous_value JSON NULL,
  new_value JSON NULL,
  actor_user_id INT UNSIGNED NULL,
  actor_role VARCHAR(40) NULL,
  actor_name VARCHAR(150) NULL,
  ip_address VARCHAR(64) NULL,
  device VARCHAR(120) NULL,
  browser VARCHAR(120) NULL,
  user_agent VARCHAR(500) NULL,
  latitude DECIMAL(10, 7) NULL,
  longitude DECIMAL(10, 7) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL,
  FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_att_audit_entity (entity_type, entity_id),
  INDEX idx_att_audit_employee (employee_id, att_date),
  INDEX idx_att_audit_created (created_at),
  INDEX idx_att_audit_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
