-- Full and final settlement.
CREATE TABLE IF NOT EXISTS final_settlements (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employee_id INT UNSIGNED NOT NULL,
  settlement_type ENUM('RESIGNATION', 'RETIREMENT', 'TERMINATION', 'DEATH', 'END_OF_CONTRACT') NOT NULL DEFAULT 'RESIGNATION',
  last_working_date DATE NOT NULL,
  notice_period_days INT UNSIGNED NULL,
  notice_served_days INT UNSIGNED NULL,
  notice_shortfall_days INT UNSIGNED NULL,
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  pending_salary DECIMAL(14, 2) NOT NULL DEFAULT 0,
  leave_encashment_days DECIMAL(6, 2) NOT NULL DEFAULT 0,
  leave_encashment_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
  gratuity_years DECIMAL(5, 2) NOT NULL DEFAULT 0,
  gratuity_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
  bonus_payable DECIMAL(14, 2) NOT NULL DEFAULT 0,
  other_earnings DECIMAL(14, 2) NOT NULL DEFAULT 0,
  notice_recovery DECIMAL(14, 2) NOT NULL DEFAULT 0,
  loan_recovery DECIMAL(14, 2) NOT NULL DEFAULT 0,
  advance_recovery DECIMAL(14, 2) NOT NULL DEFAULT 0,
  asset_recovery DECIMAL(14, 2) NOT NULL DEFAULT 0,
  tax_deduction DECIMAL(14, 2) NOT NULL DEFAULT 0,
  other_deductions DECIMAL(14, 2) NOT NULL DEFAULT 0,
  gross_payable DECIMAL(14, 2) NOT NULL DEFAULT 0,
  total_recovery DECIMAL(14, 2) NOT NULL DEFAULT 0,
  net_settlement DECIMAL(14, 2) NOT NULL DEFAULT 0,
  status ENUM('DRAFT', 'CALCULATED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'PAID') NOT NULL DEFAULT 'DRAFT',
  salary_line_id INT UNSIGNED NULL,
  clearance_json TEXT NULL,
  approved_by INT UNSIGNED NULL,
  approved_at DATETIME NULL,
  paid_at DATETIME NULL,
  remarks VARCHAR(1000) NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (salary_line_id) REFERENCES salary_lines(id) ON DELETE SET NULL,
  FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_settlements_employee (employee_id),
  INDEX idx_settlements_status (status),
  INDEX idx_settlements_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Benefits administration.
CREATE TABLE IF NOT EXISTS benefit_plans (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  benefit_type ENUM('INSURANCE', 'MEDICAL', 'RETIREMENT', 'WELLNESS', 'FLEXIBLE', 'PERK') NOT NULL DEFAULT 'INSURANCE',
  provider VARCHAR(200) NULL,
  description VARCHAR(1000) NULL,
  employer_contribution DECIMAL(12, 2) NOT NULL DEFAULT 0,
  employee_contribution DECIMAL(12, 2) NOT NULL DEFAULT 0,
  coverage_amount DECIMAL(14, 2) NULL,
  component_id INT UNSIGNED NULL,
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  effective_from DATE NULL,
  effective_to DATE NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (component_id) REFERENCES pay_components(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_benefit_plans_type (benefit_type),
  INDEX idx_benefit_plans_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS employee_benefits (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  employee_id INT UNSIGNED NOT NULL,
  plan_id INT UNSIGNED NOT NULL,
  enrolled_on DATE NOT NULL,
  ended_on DATE NULL,
  nominee_name VARCHAR(160) NULL,
  policy_number VARCHAR(80) NULL,
  employee_contribution DECIMAL(12, 2) NULL,
  employer_contribution DECIMAL(12, 2) NULL,
  status ENUM('ACTIVE', 'ENDED', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  FOREIGN KEY (plan_id) REFERENCES benefit_plans(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_employee_plan (employee_id, plan_id, enrolled_on),
  INDEX idx_employee_benefits_status (employee_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
