-- Statutory challans (the payment side) and regulatory filings (the return side).
CREATE TABLE IF NOT EXISTS statutory_challans (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  challan_no VARCHAR(60) NOT NULL,
  scheme ENUM('PF', 'ESI', 'PT', 'LWF', 'TDS') NOT NULL,
  registration_id INT UNSIGNED NULL,
  period_id INT UNSIGNED NULL,
  month_key VARCHAR(7) NULL,
  financial_year VARCHAR(9) NOT NULL,
  quarter TINYINT UNSIGNED NULL,
  state_code VARCHAR(10) NULL,
  employee_count INT UNSIGNED NOT NULL DEFAULT 0,
  total_wages DECIMAL(16, 2) NOT NULL DEFAULT 0,
  employee_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,
  employer_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,
  admin_charges DECIMAL(16, 2) NOT NULL DEFAULT 0,
  interest_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,
  penalty_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  due_date DATE NULL,
  status ENUM('DRAFT', 'GENERATED', 'PENDING_PAYMENT', 'PAID', 'ACKNOWLEDGED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
  paid_on DATE NULL,
  payment_reference VARCHAR(80) NULL,
  bank_name VARCHAR(160) NULL,
-- The generated upload file (ECR text, challan CSV) kept for the record.
  file_name VARCHAR(255) NULL,
  file_path VARCHAR(500) NULL,
  acknowledgement_no VARCHAR(80) NULL,
  acknowledged_on DATE NULL,
  remarks VARCHAR(500) NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (registration_id) REFERENCES statutory_registrations(id) ON DELETE SET NULL,
  FOREIGN KEY (period_id) REFERENCES salary_periods(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_challan (scheme, challan_no),
  INDEX idx_challans_scheme_month (scheme, month_key),
  INDEX idx_challans_status (status),
  INDEX idx_challans_due (due_date),
  INDEX idx_challans_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Regulatory filings: monthly ECR, quarterly 24Q, annual returns, registers.
CREATE TABLE IF NOT EXISTS regulatory_filings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  filing_code VARCHAR(60) NOT NULL,
  filing_type ENUM(
    'PF_ECR', 'ESI_RETURN', 'PT_RETURN', 'LWF_RETURN', 'TDS_24Q',
    'FORM_16', 'FORM_12BB', 'ANNUAL_RETURN', 'STATUTORY_REGISTER', 'OTHER'
  ) NOT NULL,
  scheme ENUM('PF', 'EPS', 'ESI', 'PT', 'LWF', 'TDS', 'MULTI') NOT NULL DEFAULT 'MULTI',
  registration_id INT UNSIGNED NULL,
  frequency ENUM('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', 'AD_HOC') NOT NULL DEFAULT 'MONTHLY',
  financial_year VARCHAR(9) NOT NULL,
  month_key VARCHAR(7) NULL,
  quarter TINYINT UNSIGNED NULL,
  period_id INT UNSIGNED NULL,
  state_code VARCHAR(10) NULL,
  due_date DATE NULL,
  employee_count INT UNSIGNED NOT NULL DEFAULT 0,
  total_amount DECIMAL(16, 2) NOT NULL DEFAULT 0,
  status ENUM(
    'NOT_STARTED', 'DRAFT', 'GENERATED', 'PENDING_APPROVAL', 'APPROVED',
    'FILED', 'ACKNOWLEDGED', 'REJECTED', 'OVERDUE'
  ) NOT NULL DEFAULT 'NOT_STARTED',
  challan_id INT UNSIGNED NULL,
  file_name VARCHAR(255) NULL,
  file_path VARCHAR(500) NULL,
  file_format VARCHAR(20) NULL,
  generated_at DATETIME NULL,
  filed_on DATE NULL,
  filed_by INT UNSIGNED NULL,
  acknowledgement_no VARCHAR(80) NULL,
  acknowledged_on DATE NULL,
-- Filing is prepared here and uploaded to the government portal by a person.
-- There is no automated e-filing integration, so this records the manual step.
  submission_mode ENUM('PORTAL_MANUAL', 'OFFLINE', 'API') NOT NULL DEFAULT 'PORTAL_MANUAL',
  rejection_reason VARCHAR(500) NULL,
  remarks VARCHAR(500) NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (registration_id) REFERENCES statutory_registrations(id) ON DELETE SET NULL,
  FOREIGN KEY (period_id) REFERENCES salary_periods(id) ON DELETE SET NULL,
  FOREIGN KEY (challan_id) REFERENCES statutory_challans(id) ON DELETE SET NULL,
  FOREIGN KEY (filed_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uk_filing (filing_type, financial_year, month_key, quarter, state_code),
  INDEX idx_filings_status (status, due_date),
  INDEX idx_filings_fy (financial_year, filing_type),
  INDEX idx_filings_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Per-employee rows inside a filing, so a return can be reproduced exactly.
CREATE TABLE IF NOT EXISTS regulatory_filing_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  filing_id INT UNSIGNED NOT NULL,
  employee_id INT UNSIGNED NOT NULL,
  identifier VARCHAR(40) NULL,
  wage_base DECIMAL(14, 2) NOT NULL DEFAULT 0,
  employee_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
  employer_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
  ncp_days DECIMAL(6, 2) NOT NULL DEFAULT 0,
  extra_json TEXT NULL,
  validation_status ENUM('VALID', 'MISSING_IDENTIFIER', 'INVALID_IDENTIFIER', 'ZERO_WAGE', 'MISSING_PAN')
    NOT NULL DEFAULT 'VALID',
  validation_message VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (filing_id) REFERENCES regulatory_filings(id) ON DELETE CASCADE,
  FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE,
  INDEX idx_filing_items_filing (filing_id, validation_status),
  INDEX idx_filing_items_employee (employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
